version: 1.2.{build}
image: Visual Studio 2017
clone_depth: 1
environment:
  sshkey:
    secure: BiD9D+ye4Q+R8yBsThsfG0K+SFL5gRx6gNfxxSTR8ge3lp98cwZ3y7T3bq7tmgE7
build_script:
- cmd: .travis\appveyor.bat
test: off