on:
  push:
    branches:
      - githubactions

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt update && sudo apt install libglu1-mesa-dev
    - name: bootstrap
      run: .ci/bootstrap.sh
