on:
  push:
    branches:
      - githubactions

jobs:
  macos-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap compiler
      run: .ci/bootstrap.sh osx
    - name: Compile
      run: .ci/compile.sh
