on:
  push:
    branches:
      - development
      - ci-test

jobs:
  linux-build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'ci-skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt update && sudo apt install libglu1-mesa-dev libncurses-dev
    - name: Bootstrap compiler
      run: .ci/bootstrap.sh lnx
    - name: Compile
      run: .ci/compile.sh
    - name: Update source
      if: github.event_name == 'push'
      run: .ci/update-source.sh
    - name: Push to repository
      if: github.event_name == 'push'
      uses: ad-m/github-push-action@19caa5c351f47734055690f7d01aaaef2f9114d5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: development
    - name: Set deployment SSH key
      if: github.event_name == 'push'
      uses: shimataro/ssh-key-action@v2.1.0
      with:
        key: ${{ secrets.SSH_KEY }}
        # "qb64.org ssh-rsa AAAA" etc.
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: |
          Host remote-server
          HostName qb64.org
          User m6rosupy1q2t
    - name: Package and deploy
      if: github.event_name == 'push'
      run: .ci/deploy.sh lnx

  macos-build:
    runs-on: macos-latest
    if: "contains(github.event.head_commit.message, 'ci-skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap compiler
      run: .ci/bootstrap.sh osx
    - name: Compile
      run: .ci/compile.sh
    - name: Set deployment SSH key
      if: github.event_name == 'push'
      uses: shimataro/ssh-key-action@v2.1.0
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: |
          Host remote-server
          HostName qb64.org
          User m6rosupy1q2t
    - name: Package and deploy
      if: github.event_name == 'push'
      run: .ci/deploy.sh osx

  windows-x86-build:
    runs-on: windows-latest
    if: "contains(github.event.head_commit.message, 'ci-skip')"
    env:
      PLATFORM: x86
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap compiler
      run: .ci/bootstrap.bat
    - name: Compile
      run: .ci/compile.bat
    - name: Set deployment SSH key
      if: github.event_name == 'push'
      uses: shimataro/ssh-key-action@v2.1.0
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: |
          Host remote-server
          HostName qb64.org
          User m6rosupy1q2t
    - name: Package and deploy
      if: github.event_name == 'push'
      run: .ci/deploy.bat

  windows-x64-build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    env:
      PLATFORM: x64
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap compiler
      run: .ci/bootstrap.bat
    - name: Compile
      run: .ci/compile.bat
    - name: Set deployment SSH key
      if: github.event_name == 'push'
      uses: shimataro/ssh-key-action@v2.1.0
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: |
          Host remote-server
          HostName qb64.org
          User m6rosupy1q2t
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "alfovmeof" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
    - name: Package and deploy
      if: github.event_name == 'push'
      run: .ci/deploy.bat
