on:
  push:
    branches:
      - development

jobs:
  linux-build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt update && sudo apt install libglu1-mesa-dev libncurses-dev
    - name: Bootstrap compiler
      run: .ci/bootstrap.sh lnx
    - name: Compile
      run: .ci/compile.sh
    - name: Update source
      if: github.event_name == 'push'
      run: .ci/update-source.sh
    - name: Push to repository
      if: github.event_name == 'push'
      uses: ad-m/github-push-action@19caa5c351f47734055690f7d01aaaef2f9114d5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: development
    - name: Set deployment SSH key
      if: github.event_name == 'push'
      uses: shimataro/ssh-key-action@v2.1.0
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: "qb64.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDV1rDTpxtQDosKL7CMwxtICwjAizgpyxNd1SuvKAO3VCFLL52H4IAbahW8P1KPL4zCN0tL4BNdNDXCa/y/884NVVx1IRBFTVQaRm0+ZypG/WoNXElPANu95GAwexVdRQFITVyfdU2GWm6ch7AFnPYte7WJCQo4nV1b/Hh3Ra0muZjxJRTmRGa0Y2u5txlGvTjyYsM+MZ65jFuISs0qSxS9UPNjElW43HX9YyKGij8rQD+pWBFonDf1i0X9gvoVNbTM9pkSo5t8cVN/TU+tWjjhUw+L5P0vWkahQAMDnHDFzmK3V8cIHcSA3uGVIgGZvphTZ6CFk984JtWvCIGGJxG/q4lDxVDLddCfnBXFErMeHTw61AFVOLdXF7n4xz+Spy9kvgtHyOJodWxRjSWAMGL4T09WOXD0Cy8hX03Si9Pq6EnHGnVv6r1mIG56LCmeTPFhsBVtL+X63MQdG7+vKXM+2RbXr1N+IQvnE4asNJkRTeLiwe86sojiTxcexIxMus8UZ6co94ZNImP585/na1k5G7ke5ihDsLIbx9kKGS1V582A7VpX3Ci0iQ6LqZLII4ruR2swjQnzxeP0k5QPdBISZXvaKkqRBlVaSbpubxQBKvL3MNugJTPaeQimYnhQmnxDltfvGuErM9XHK0TMCSMrEXmN+MFecwUAEmgzl8VW2w== autobuilds-qb64"
        config: |
          Host remote-server
          HostName qb64.org
          User m6rosupy1q2t
    - name: Package and deploy
      if: github.event_name == 'push'
      run: .ci/deploy.sh lnx

  macos-build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap compiler
      run: .ci/bootstrap.sh osx
    - name: Compile
      run: .ci/compile.sh
    - name: Set deployment SSH key
      if: github.event_name == 'push'
      uses: shimataro/ssh-key-action@v2.1.0
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: "qb64.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDV1rDTpxtQDosKL7CMwxtICwjAizgpyxNd1SuvKAO3VCFLL52H4IAbahW8P1KPL4zCN0tL4BNdNDXCa/y/884NVVx1IRBFTVQaRm0+ZypG/WoNXElPANu95GAwexVdRQFITVyfdU2GWm6ch7AFnPYte7WJCQo4nV1b/Hh3Ra0muZjxJRTmRGa0Y2u5txlGvTjyYsM+MZ65jFuISs0qSxS9UPNjElW43HX9YyKGij8rQD+pWBFonDf1i0X9gvoVNbTM9pkSo5t8cVN/TU+tWjjhUw+L5P0vWkahQAMDnHDFzmK3V8cIHcSA3uGVIgGZvphTZ6CFk984JtWvCIGGJxG/q4lDxVDLddCfnBXFErMeHTw61AFVOLdXF7n4xz+Spy9kvgtHyOJodWxRjSWAMGL4T09WOXD0Cy8hX03Si9Pq6EnHGnVv6r1mIG56LCmeTPFhsBVtL+X63MQdG7+vKXM+2RbXr1N+IQvnE4asNJkRTeLiwe86sojiTxcexIxMus8UZ6co94ZNImP585/na1k5G7ke5ihDsLIbx9kKGS1V582A7VpX3Ci0iQ6LqZLII4ruR2swjQnzxeP0k5QPdBISZXvaKkqRBlVaSbpubxQBKvL3MNugJTPaeQimYnhQmnxDltfvGuErM9XHK0TMCSMrEXmN+MFecwUAEmgzl8VW2w== autobuilds-qb64"
        config: |
          Host remote-server
          HostName qb64.org
          User m6rosupy1q2t
    - name: Package and deploy
      if: github.event_name == 'push'
      run: .ci/deploy.sh osx

  windows-x86-build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    env:
      PLATFORM: x86
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap compiler
      run: .ci/bootstrap.bat
    - name: Compile
      run: .ci/compile.bat
    - name: Set deployment SSH key
      if: github.event_name == 'push'
      uses: shimataro/ssh-key-action@v2.1.0
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: "qb64.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDV1rDTpxtQDosKL7CMwxtICwjAizgpyxNd1SuvKAO3VCFLL52H4IAbahW8P1KPL4zCN0tL4BNdNDXCa/y/884NVVx1IRBFTVQaRm0+ZypG/WoNXElPANu95GAwexVdRQFITVyfdU2GWm6ch7AFnPYte7WJCQo4nV1b/Hh3Ra0muZjxJRTmRGa0Y2u5txlGvTjyYsM+MZ65jFuISs0qSxS9UPNjElW43HX9YyKGij8rQD+pWBFonDf1i0X9gvoVNbTM9pkSo5t8cVN/TU+tWjjhUw+L5P0vWkahQAMDnHDFzmK3V8cIHcSA3uGVIgGZvphTZ6CFk984JtWvCIGGJxG/q4lDxVDLddCfnBXFErMeHTw61AFVOLdXF7n4xz+Spy9kvgtHyOJodWxRjSWAMGL4T09WOXD0Cy8hX03Si9Pq6EnHGnVv6r1mIG56LCmeTPFhsBVtL+X63MQdG7+vKXM+2RbXr1N+IQvnE4asNJkRTeLiwe86sojiTxcexIxMus8UZ6co94ZNImP585/na1k5G7ke5ihDsLIbx9kKGS1V582A7VpX3Ci0iQ6LqZLII4ruR2swjQnzxeP0k5QPdBISZXvaKkqRBlVaSbpubxQBKvL3MNugJTPaeQimYnhQmnxDltfvGuErM9XHK0TMCSMrEXmN+MFecwUAEmgzl8VW2w== autobuilds-qb64"
        config: |
          Host remote-server
          HostName qb64.org
          User m6rosupy1q2t
    - name: Package and deploy
      if: github.event_name == 'push'
      run: .ci/deploy.bat

  windows-x64-build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    env:
      PLATFORM: x64
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap compiler
      run: .ci/bootstrap.bat
    - name: Compile
      run: .ci/compile.bat
    - name: Set deployment SSH key
      if: github.event_name == 'push'
      uses: shimataro/ssh-key-action@v2.1.0
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: "qb64.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDV1rDTpxtQDosKL7CMwxtICwjAizgpyxNd1SuvKAO3VCFLL52H4IAbahW8P1KPL4zCN0tL4BNdNDXCa/y/884NVVx1IRBFTVQaRm0+ZypG/WoNXElPANu95GAwexVdRQFITVyfdU2GWm6ch7AFnPYte7WJCQo4nV1b/Hh3Ra0muZjxJRTmRGa0Y2u5txlGvTjyYsM+MZ65jFuISs0qSxS9UPNjElW43HX9YyKGij8rQD+pWBFonDf1i0X9gvoVNbTM9pkSo5t8cVN/TU+tWjjhUw+L5P0vWkahQAMDnHDFzmK3V8cIHcSA3uGVIgGZvphTZ6CFk984JtWvCIGGJxG/q4lDxVDLddCfnBXFErMeHTw61AFVOLdXF7n4xz+Spy9kvgtHyOJodWxRjSWAMGL4T09WOXD0Cy8hX03Si9Pq6EnHGnVv6r1mIG56LCmeTPFhsBVtL+X63MQdG7+vKXM+2RbXr1N+IQvnE4asNJkRTeLiwe86sojiTxcexIxMus8UZ6co94ZNImP585/na1k5G7ke5ihDsLIbx9kKGS1V582A7VpX3Ci0iQ6LqZLII4ruR2swjQnzxeP0k5QPdBISZXvaKkqRBlVaSbpubxQBKvL3MNugJTPaeQimYnhQmnxDltfvGuErM9XHK0TMCSMrEXmN+MFecwUAEmgzl8VW2w== autobuilds-qb64"
        config: |
          Host remote-server
          HostName qb64.org
          User m6rosupy1q2t
    - name: Package and deploy
      if: github.event_name == 'push'
      run: .ci/deploy.bat
